services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_CSE_API_KEY=${GOOGLE_CSE_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:5173"
