# Generated by Django 5.0.1 on 2024-03-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, verbose_name='Title')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('manufacturer', models.CharField(default='', max_length=256, verbose_name='Manufacturer')),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
        ),
    ]
