# Generated by Django 5.0.1 on 2024-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleAmazone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(db_index=True, default='', help_text='Column name', max_length=256, verbose_name='Col')),
                ('row', models.CharField(db_index=True, default='', help_text='Column name', max_length=256, verbose_name='Row')),
                ('value', models.FloatField(default=0, help_text='Value of the recommendation', verbose_name='Value')),
            ],
            options={
                'unique_together': {('col', 'row')},
            },
        ),
    ]
