# Generated by Django 5.0.4 on 2024-04-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleAmazone', '0002_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='value',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='description_similarity',
            field=models.FloatField(default=0.0, verbose_name='Description Cosine Similarity'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='title_similarity',
            field=models.FloatField(default=0.0, verbose_name='Title Cosine Similarity'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='col',
            field=models.CharField(db_index=True, help_text='Product ID of product to recommend for', max_length=100, verbose_name='Col'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='row',
            field=models.CharField(db_index=True, help_text='Product ID of product to compare with', max_length=100, verbose_name='Row'),
        ),
        migrations.AddIndex(
            model_name='recommendations',
            index=models.Index(fields=['col', 'row'], name='GoogleAmazo_col_5ae8f6_idx'),
        ),
    ]
