# Generated by Django 5.0.1 on 2024-04-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleAmazone', '0003_remove_recommendations_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(default='https://www.pinclipart.com/picdir/middle/205-2052870_caution-cartoon-png-clipart.png', upload_to=''),
        ),
    ]
