# Generated by Django 5.0.1 on 2024-04-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleAmazone', '0004_products_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.URLField(default='https://www.pinclipart.com/picdir/middle/205-2052870_caution-cartoon-png-clipart.png', max_length=255),
        ),
    ]
